### PR TITLE
[DEVX-1675] docs: add contributing guide

### PR DESCRIPTION
**Pull request by r0binary**
* this generic information is true for all of Pleo's repos and should therefore managed here to be populated across all repos automatically

### CODE REVIEW

**Review by marcos-arranz — APPROVED** [review]

**Comment by r0binary** [comment]
Sorry I forgot to add context to the commit message. Here's what github can do for us: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#creating-a-repository-for-default-files

**Review by VictorPascualV — APPROVED** [review]

**Comment by VictorPascualV** [comment]
Much nicer that having to copy-paste across dozens of repos 😩

**Comment by VictorPascualV** [comment]
@r0binary will that add the CONTRIBUTING.md file to all existing repositories? or only to the ones that we create from now on?

**Comment by r0binary** [comment]
> @r0binary will that add the CONTRIBUTING.md file to all existing repositories? or only to the ones that we create from now on?

I'm not 100% sure, but I think in all repos that do not have an own CONTRIBUTING.md.
Here's an excerpt from the docs:

> GitHub will use and display default files for any repository owned by the account that does not have its own file of that type in any of the following places:
>    The root of the repository
>    The .github folder
>    The docs folder

Please that (if I understand this correctly) the files are displayed as kind of an overlay to other repos. They are not really there and won't show up in the sources on repo clone

**Comment by r0binary** [comment]
@VictorPascualV I see the contributing guidelines show up correctly when I create an issue let's say in [renovate-config](https://github.com/pleo-io/renovate-config/issues/new) (which does not have an own CONTRIBUTING.md). However, it does not show up in the file explorer in any way (the docs mention this, but I though they would refer to the local clone of a repo). From what I understand we actually want to have the file present in every repo, right? If so, we might have another option to go with centralized-templates instead to keep a single source of truth, but it won't get us to Gold any faster. Do you still see some value in the CONTRIBUTING.md in this very repo or should I revert my changes?

**Pull request merged**
